language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t patou/docker-appengine-java8-maven .

script:
  - docker run -d -p 127.0.0.1:80:4567 patou/docker-appengine-java8-maven /bin/sh -c "appcfg.sh --help"

after_success:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASS"
  - docker push patou/docker-appengine-java8-maven
